version: 0.1.0.{build}
branches:
  only:
    - master

environment:
  CLI_VERSION: latest
  CLI_ARCH: x64
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNETCLI_ZIP_NAME: dotnet-sdk-latest-win-x64.zip
  DOTNETCLI_ZIP_URL: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/
  DOTNET_INSTALL_DIR: "$pwd\\.dotnetcli"
  PROCMON_ZIP_NAME: ProcessMonitor.zip
  PROCMON_ZIP_URL: https://download.sysinternals.com/files/
  PROCMON_INSTALL_DIR: "$pwd\\.procmon"

install:
  - ps: Start-FileDownload "$env:DOTNETCLI_ZIP_URL$env:DOTNETCLI_ZIP_NAME"
  - ps: Start-FileDownload "$env:PROCMON_ZIP_URL$env:PROCMON_ZIP_NAME"
  - 7z x %DOTNETCLI_ZIP_NAME% -y -o"%DOTNET_INSTALL_DIR%"
  - 7z x %PROCMON_ZIP_NAME% -y -o"%APPVEYOR_BUILD_FOLDER%"
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  - ps: Install-Product node 8.2.1

build_script:
  - where procmon
  - where dotnet
  - dotnet --info
  - npm install
  - powershell -NonInteractive -NoProfile -File .\DumpDlls.ps1
  - dotnet restore ConsoleApp1
  - dotnet publish -r win10-x64 -f netcoreapp1.1 -c Release ConsoleApp1\ConsoleApp1.sln
  - powershell -NonInteractive -NoProfile -File .\PackageDlls.ps1

test_script:
  - dotnet run -p .\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj
  - ConsoleApp1\ConsoleApp1\bin\Release\netcoreapp1.1\win10-x64\publish\ConsoleApp1.exe
