# https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md

version: 0.1.0.{build}
branches:
  only:
    - master

environment:
  CLI_VERSION: latest
  CLI_ARCH: x64
  DOTNETCLI_ZIP_NAME: dotnet-sdk-latest-win-x64.zip
  DOTNETCLI_ZIP_URL: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/
  DOTNET_INSTALL_DIR: "$pwd\\.dotnetcli"
  PROCMON_ZIP_NAME: ProcessMonitor.zip
  PROCMON_ZIP_URL: https://download.sysinternals.com/files/
  PROCMON_INSTALL_DIR: "$pwd\\.procmon"

install:
  - ps: Start-FileDownload "$env:DOTNETCLI_ZIP_URL$env:DOTNETCLI_ZIP_NAME"
  - 7z x %DOTNETCLI_ZIP_NAME% -y -o"%DOTNET_INSTALL_DIR%"
  - ps: Start-FileDownload "$env:PROCMON_ZIP_URL$env:PROCMON_ZIP_NAME"
  - 7z x %PROCMON_ZIP_NAME% -y -o"%PROCMON_INSTALL_DIR%"
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:PROCMON_INSTALL_DIR;$env:Path"
  # see https://github.com/enricosada/fsharp-dotnet-cli-samples/blob/master/appveyor.yml
  # Download install script to install .NET cli in .dotnet dir
  # - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/v1.0.4/scripts/obtain/dotnet-install.ps1" -OutFile "$pwd/install.ps1"
  # - ps: '& ./install.ps1 -Channel Release -Version "1.0.4" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  # - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

# need build_script, or appveyor starts looking for a sln file

build_script:
  - where procmon
  - where dotnet
  - dotnet --info
  # - .\DumpDlls.ps1
  - dotnet clean ConsoleApp1
  - ps: start-process "procmon.exe" -ArgumentList "/accepteula","/quiet","/minimized","/loadconfig procmon-conf.pmc","/backingfile data.pml"
  - ps: start-process "procmon.exe" -ArgumentList "/waitforidle" -wait
  - dotnet build ConsoleApp1
  - ps: start-process "procmon.exe" -ArgumentList "/terminate" -wait
  - ps: start-process "procmon.exe" -ArgumentList "/openlog","data.pml","/saveapplyfilter","/saveas data.csv" -wait
  - node process-raw.js data.csv > ConsoleApp1\ConsoleApp1\dlls.json
  - ps: remove-item (Get-Item data.csv)
  - ps: remove-item (Get-Item *.pml) # might generate more then one pml file


  - type ConsoleApp1\ConsoleApp1\dlls.json
  - dotnet restore ConsoleApp1
  - dotnet build ConsoleApp1\ConsoleApp1.sln
  - dotnet run -p .\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj